development:
  adapter: postgresql
  database: checked_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: checked_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: checked_production
  pool: 5
  timeout: 5000